# Generated by Django 4.2.5 on 2023-09-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(max_length=100)),
                ('groom_name', models.CharField(max_length=100)),
                ('wedding_date', models.DateField()),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
